Session validation for IKS
IBM/ibmcloud-volume-vpc pull request #30
Opened 2021-08-11 04:28 UTC by sameshai

2021-08-11 04:30 UTC, sameshai commented
Negative test case --

{“level”:“info”,“ts”:“2021-08-10T16:15:51.001+0530",“caller”:“utils/init_provider.go:91",“msg”:“Calling provider/utils/init_provider.go GenerateContextCredentials”,“RequestID”:“1b913077-be44-4617-a9b8-888bd6ab89b9"}
{“level”:“info”,“ts”:“2021-08-10T16:15:51.001+0530",“caller”:“utils/init_provider.go:106",“msg”:“Generating generateContextCredentials for “,”RequestID”:“1b913077-be44-4617-a9b8-888bd6ab89b9”,“Provider ID”:“iks-vpc-classic”}
{“level”:“info”,“ts”:“2021-08-10T16:15:51.001+0530”,“caller”:“provider/provider.go:68”,“msg”:“Entering IksVpcBlockProvider.OpenSession”,“RequestID”:“1b913077-be44-4617-a9b8-888bd6ab89b9”}
{“level”:“info”,“ts”:“2021-08-10T16:15:51.001+0530”,“caller”:“provider/provider.go:73”,“msg”:“Opening VPC block session”,“RequestID”:“1b913077-be44-4617-a9b8-888bd6ab89b9”}
{“level”:“info”,“ts”:“2021-08-10T16:15:51.001+0530”,“caller”:“provider/provider.go:75”,“msg”:“Its IKS dual session. Getttng IAM token for VPC block session”,“RequestID”:“1b913077-be44-4617-a9b8-888bd6ab89b9”}
{“level”:“info”,“ts”:“2021-08-10T16:15:51.001+0530”,“caller”:“iam/token_exchange_iks.go:132”,“msg”:“In tokenExchangeIKSRequest’s sendTokenExchangeRequest()“,”RequestID”:“1b913077-be44-4617-a9b8-888bd6ab89b9”}
{“level”:“info”,“ts”:“2021-08-10T16:15:51.001+0530”,“caller”:“iam/token_exchange_iks.go:151”,“msg”:“Sending IAM token exchange request to container api server”,“RequestID”:“1b913077-be44-4617-a9b8-888bd6ab89b9”}
{“level”:“info”,“ts”:“2021-08-10T16:15:53.467+0530”,“caller”:“provider/provider.go:177”,“msg”:“Entering OpenSession”,“RequestID”:“1b913077-be44-4617-a9b8-888bd6ab89b9”}
{“level”:“info”,“ts”:“2021-08-10T16:15:53.467+0530”,“caller”:“provider/provider.go:200”,“msg”:“”,“RequestID”:“1b913077-be44-4617-a9b8-888bd6ab89b9”,“apiConfig.ContextID”:“1b913077-be44-4617-a9b8-888bd6ab89b9”}
{“level”:“info”,“ts”:“2021-08-10T16:15:53.467+0530”,“caller”:“metrics/metrics.go:73”,“msg”:“Time to complete”,“RequestID”:“1b913077-be44-4617-a9b8-888bd6ab89b9”,“OpenSession”:0.000066305}
{“level”:“info”,“ts”:“2021-08-10T16:15:53.467+0530",“caller”:“provider/provider.go:88",“msg”:“Opening IKS block session”,“RequestID”:“1b913077-be44-4617-a9b8-888bd6ab89b9"}
{“level”:“info”,“ts”:“2021-08-10T16:15:53.467+0530",“caller”:“provider/provider.go:99",“msg”:“Its ISK dual session. Getttng IAM token for IKS block session”,“RequestID”:“1b913077-be44-4617-a9b8-888bd6ab89b9"}
{“level”:“warn”,“ts”:“2021-08-10T16:15:53.467+0530",“caller”:“provider/provider.go:102",“msg”:“Error occurred while generating IAM token for IKS. But continue with VPC session alone. \n Volume Mount operation will fail but volume provisioning will work”,“RequestID”:“1b913077-be44-4617-a9b8-888bd6ab89b9"}
Enter the volume id: 11
Enter the instance id: 11
Enter the cluster id: 11
{"level":"warn","ts":"2021-08-10T16:16:01.977+0530","caller":"provider/attach_volume.go:49","msg":"Provider Session is not valid.","RequestID":"1b913077-be44-4617-a9b8-888bd6ab89b9"}
{"level":"info","ts":"2021-08-10T16:16:01.978+0530","caller":"metrics/metrics.go:73","msg":"Time to complete","RequestID":"1b913077-be44-4617-a9b8-888bd6ab89b9","AttachVolume":0.000171531}
{"level":"error","ts":"2021-08-10T16:16:01.978+0530","caller":"samples/attach_detach.go:51","msg":"Failed to attach the volume: ","RequestID":"1b913077-be44-4617-a9b8-888bd6ab89b9","error":"{Code:InvalidServiceSession, Type:RetrivalFailed, Description:The Service Session was not found due to error while generating IAM token for Sesssion Service., BackendError:IAM token exchange request failed,\"RequestID\":\"d5f38c32-cb9f-4e3b-8cd8-ff3b86335e62\",\"ResponseError\":\"json: unsupported type: func() (io.ReadCloser, error)\",\"error\":\"Error response from server. Status code: 503; message: upstream connect error or disconnect/reset before headers. reset reason: local reset, RC:500}"}

2021-08-11 04:30 UTC, sameshai commented
Ideally we should return nil session for IKS if there is issue but today we can't do this as we have IKS and VPC session in same object. In future we need to separate out these for better error handling

2021-08-18 08:28 UTC, meghnasiingh approved these changes
LGTM

2021-08-18 10:24 UTC, arahamad requested changes
can you check these improvements

2021-08-18 10:24 UTC, arahamad commented on block/provider/attach_volume_test.go
> +				volumeAttachService.ListVolumeAttachmentsReturns(testcase.baseVolumeAttachmentsListResponse, errors.New(testcase.expectedReasonCode))
can we optimize this if condition

2021-08-18 10:24 UTC, arahamad commented on block/provider/detach_volume_test.go
> + * Copyright 2020 IBM Corp.
change year to 2021

2021-08-18 10:24 UTC, arahamad commented on common/messages/messages_en.go
> +		Description: "The Service Session was not found due to error while generating IAM token for Sesssion Service.",
can it be `The Service Session was not found due to error while generating IAM token`

2021-08-19 06:02 UTC, sameshai commented on block/provider/attach_volume_test.go
> +			testCaseName: "Volume Attachment does not exist for the Volume ID- List Vol Attachement Fails",
Verify this if really required

2021-08-19 06:05 UTC, sameshai commented on block/provider/attach_volume_test.go
> +	assert.NotNil(t, err)
Error code validation

2021-08-19 06:10 UTC, sameshai commented on block/provider/detach_volume_test.go
> +			},
Check this

2021-08-19 08:34 UTC, arahamad approved these changes
looks to be some more improvement required in unit tests, will take that later

2021-08-19 08:34 UTC, arahamad commented on block/provider/attach_volume_test.go
> +					Volume: &models.Volume{ID: "volume-id123"},
looks volume name need to be updated here

2021-08-19 08:35 UTC, merged