API-key-rotation-update-api-ke
IBM/ibmcloud-volume-vpc pull request #33
Opened 2021-11-26 10:10 UTC by GunaKKIBM

2021-11-29 13:54 UTC, ambiknai reviewed
lgtm

2021-11-30 05:56 UTC, sameshai commented on go.mod
> +	github.com/IBM/ibmcloud-volume-interface v1.0.1-0.20211130042446-32c5e8b6904f
Once we push the interface PR please make sure we update the release

2021-11-30 05:56 UTC, sameshai approved these changes
LGTM

2021-11-30 17:32 UTC, contsto commented
:red_circle: Coverage decreased from [90.3279%] to [90.0382%]

2021-12-01 13:41 UTC, contsto commented
:red_circle: Coverage decreased from [90.3279%] to [89.9676%]

2021-12-02 05:42 UTC, contsto commented
:red_circle: Coverage decreased from [90.3279%] to [89.9676%]

2021-12-02 06:38 UTC, prankulmahajan commented on go.mod
> +)
I think we can remove this, since we have removed csi-common reference

2021-12-02 11:57 UTC, contsto commented
:red_circle: Coverage decreased from [90.3279%] to [89.9676%]

2021-12-02 12:00 UTC, contsto commented
:red_circle: Coverage decreased from [90.3279%] to [89.9676%]

2021-12-03 10:38 UTC, contsto commented
:thumbsup: Coverage increased from [90.3279%] to [90.4235%]

2021-12-03 11:57 UTC, contsto commented
:thumbsup: Coverage increased from [90.3279%] to [90.3926%]

2021-12-03 13:35 UTC, GunaKKIBM commented
Test results:

Creating pvc by deleting api key, initially, the pvc is in pending state, kubernetes retries to create volume. Meanwhile, if the api key is reset, volume gets created. It won't be necessary to restart the pod. 
```
kubectl create -f pvc.yaml                                   
persistentvolumeclaim/csi-vpc-block-5iops-pvc-api-key-rotation40 created

gunakk@Gunas-MBP OPENSHIFT_VPC_CLUSTER_TESTING % kubectl describe pvc csi-vpc-block-5iops-pvc-api-key-rotation40 
Name:          csi-vpc-block-5iops-pvc-api-key-rotation40
Namespace:     default
StorageClass:  ibmc-vpc-block-5iops-tier
Status:        Bound
Volume:        pvc-d7da1591-4aec-474a-b5f2-a406fe4b815c
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      10Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason                 Age                   From                                                                                      Message
  ----     ------                 ----                  ----                                                                                      -------
  Warning  ProvisioningFailed     3m29s                 vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_1d3a9aa8-1bc4-4e29-90cc-1e07d9edfef1  failed to provision volume with StorageClass "ibmc-vpc-block-5iops-tier": rpc error: code = Internal desc = {RequestID: 9d2c7752-c1e4-491a-a61f-fbb45a30b7d7 , Code: InternalError, Description: Internal error occurred, BackendError: API key is not found, reset the api key. If reset, retry after few minutes, Action: Please check 'BackendError' tag for more details}
  Warning  ProvisioningFailed     2m29s                 vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_1d3a9aa8-1bc4-4e29-90cc-1e07d9edfef1  failed to provision volume with StorageClass "ibmc-vpc-block-5iops-tier": rpc error: code = Internal desc = {RequestID: 077e111a-e15c-46d4-a54e-0abc0cf919d7 , Code: InternalError, Description: Internal error occurred, BackendError: API key is not found, reset the api key. If reset, retry after few minutes, Action: Please check 'BackendError' tag for more details}
  Normal   Provisioning           88s (x4 over 4m29s)   vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_1d3a9aa8-1bc4-4e29-90cc-1e07d9edfef1  External provisioner is provisioning volume for claim "default/csi-vpc-block-5iops-pvc-api-key-rotation40"
  Warning  ProvisioningFailed     88s                   vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_1d3a9aa8-1bc4-4e29-90cc-1e07d9edfef1  failed to provision volume with StorageClass "ibmc-vpc-block-5iops-tier": rpc error: code = Internal desc = {RequestID: b1c7a84a-04ec-4f74-be16-47ef86202d18 , Code: InternalError, Description: Internal error occurred, BackendError: API key is not found, reset the api key. If reset, retry after few minutes, Action: Please check 'BackendError' tag for more details}
  Normal   ExternalProvisioning   20s (x18 over 4m29s)  persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "vpc.block.csi.ibm.io" or manually created by system administrator
  Normal   ProvisioningSucceeded  11s                   vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_1d3a9aa8-1bc4-4e29-90cc-1e07d9edfef1  Successfully provisioned volume pvc-d7da1591-4aec-474a-b5f2-a406fe4b815c

 % kubectl create -f validPOD2.yaml
deployment.apps/api-key-rotation-pod40 created

 % kubectl get pods
NAME                                      READY   STATUS             RESTARTS   AGE
api-key-rotation-pod40-6fff7bb57-vmnxn    1/1     Running            0          3m26s
```

2021-12-06 07:51 UTC, arahamad requested changes
pl check comments

2021-12-06 07:51 UTC, arahamad commented on block/utils/init_provider.go
>  	if err == nil {
make it uniform accros other conditions

2021-12-06 07:51 UTC, arahamad commented on go.sum
> +github.com/IBM/ibmcloud-volume-interface v1.0.1-0.20211203045519-74fe99e68e4f h1:XcW0pted1N9FWNhtspx38USjCmWduICvngyeU/OZ34g=
update this

2021-12-06 10:38 UTC, prankulmahajan approved these changes
lgtm

2021-12-06 10:41 UTC, contsto commented
:thumbsup: Coverage increased from [90.3279%] to [90.3926%]

2021-12-06 10:47 UTC, arahamad approved these changes
lgtm

2021-12-06 10:53 UTC, merged