csi-controller-0 pod CrashLoopBackoff Error (GHE 2749) --AttachVolume…
IBM/ibmcloud-volume-vpc pull request #35
Opened 2021-12-16 08:16 UTC by sameshai

… call returns empty attachment response, handle nil pointer condition

2021-12-16 08:23 UTC, sameshai commented
```
{"level":"info","timestamp":"2021-12-15T17:20:57.260Z","caller":"cmd/main.go:84","msg":"IBM CSI driver version","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver","DriverVersion":"vpcBlockDriver-"}
{"level":"info","timestamp":"2021-12-15T17:20:57.260Z","caller":"cmd/main.go:85","msg":"Controller Mutex Lock enabled","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver","LockEnabled":false}
{"level":"info","timestamp":"2021-12-15T17:20:57.260Z","caller":"ibmcloudprovider/volume_provider.go:48","msg":"NewIBMCloudStorageProvider-Reading provider configuration...","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver"}
{"level":"info","timestamp":"2021-12-15T17:20:57.260Z","caller":"config/config.go:63","msg":"parsing conf file","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver","confpath":"/etc/storage_ibmc/slclient.toml"}
{"level":"warn","timestamp":"2021-12-15T17:20:57.262Z","caller":"ibmcloudprovider/volume_provider.go:60","msg":"Failed to parse VPC_API_VERSION, setting default value","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver"}
{"level":"info","timestamp":"2021-12-15T17:20:57.262Z","caller":"ibmcloudprovider/volume_provider.go:65","msg":"Fetching clusterInfo","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver"}
{"level":"info","timestamp":"2021-12-15T17:20:57.263Z","caller":"ibmcloudprovider/volume_provider.go:72","msg":"Fetched clusterInfo..","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver"}
{"level":"info","timestamp":"2021-12-15T17:20:57.263Z","caller":"utils/init_provider.go:42","msg":"Configuring VPC Block Provider","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver"}
{"level":"info","timestamp":"2021-12-15T17:20:57.263Z","caller":"provider/provider.go:74","msg":"Entering NewProvider","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver"}
{"level":"info","timestamp":"2021-12-15T17:20:57.263Z","caller":"utils/init_provider.go:54","msg":"Configuring IKS-VPC Block Provider","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver"}
{"level":"info","timestamp":"2021-12-15T17:20:57.263Z","caller":"provider/provider.go:74","msg":"Entering NewProvider","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver"}
{"level":"info","timestamp":"2021-12-15T17:20:57.263Z","caller":"provider/provider.go:74","msg":"Entering NewProvider","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver"}
{"level":"info","timestamp":"2021-12-15T17:20:57.263Z","caller":"utils/init_provider.go:65","msg":"Provider registration done!!!","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver"}
{"level":"info","timestamp":"2021-12-15T17:20:57.263Z","caller":"ibmcloudprovider/volume_provider.go:125","msg":"Successfully read provider configuration","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver"}
{"level":"info","timestamp":"2021-12-15T17:20:57.323Z","caller":"ibmcsidriver/ibm_csi_driver.go:49","msg":"IBMCSIDriver-SetupIBMCSIDriver setting up IBM CSI Driver...","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver"}
{"level":"info","timestamp":"2021-12-15T17:20:57.323Z","caller":"ibmcsidriver/ibm_csi_driver.go:115","msg":"IBMCSIDriver-AddVolumeCapabilityAccessModes...","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver","VolumeCapabilityAccessModes":[1]}
{"level":"info","timestamp":"2021-12-15T17:20:57.323Z","caller":"ibmcsidriver/ibm_csi_driver.go:118","msg":"Enabling volume access mode","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver","Mode":"SINGLE_NODE_WRITER"}
{"level":"info","timestamp":"2021-12-15T17:20:57.323Z","caller":"ibmcsidriver/ibm_csi_driver.go:122","msg":"Successfully enabled Volume Capability Access Modes","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver"}
{"level":"info","timestamp":"2021-12-15T17:20:57.323Z","caller":"ibmcsidriver/ibm_csi_driver.go:128","msg":"IBMCSIDriver-AddControllerServiceCapabilities...","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver","ControllerServiceCapabilities":[1,2,3,9]}
{"level":"info","timestamp":"2021-12-15T17:20:57.323Z","caller":"ibmcsidriver/ibm_csi_driver.go:131","msg":"Adding controller service capability","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver","Capability":"CREATE_DELETE_VOLUME"}
{"level":"info","timestamp":"2021-12-15T17:20:57.323Z","caller":"ibmcsidriver/ibm_csi_driver.go:131","msg":"Adding controller service capability","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver","Capability":"PUBLISH_UNPUBLISH_VOLUME"}
{"level":"info","timestamp":"2021-12-15T17:20:57.323Z","caller":"ibmcsidriver/ibm_csi_driver.go:131","msg":"Adding controller service capability","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver","Capability":"LIST_VOLUMES"}
{"level":"info","timestamp":"2021-12-15T17:20:57.323Z","caller":"ibmcsidriver/ibm_csi_driver.go:131","msg":"Adding controller service capability","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver","Capability":"EXPAND_VOLUME"}
{"level":"info","timestamp":"2021-12-15T17:20:57.323Z","caller":"ibmcsidriver/ibm_csi_driver.go:135","msg":"Successfully added Controller Service Capabilities","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver"}
{"level":"info","timestamp":"2021-12-15T17:20:57.323Z","caller":"ibmcsidriver/ibm_csi_driver.go:141","msg":"IBMCSIDriver-AddNodeServiceCapabilities...","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver","NodeServiceCapabilities":[1,2,3]}
{"level":"info","timestamp":"2021-12-15T17:20:57.323Z","caller":"ibmcsidriver/ibm_csi_driver.go:144","msg":"Adding node service capability","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver","NodeServiceCapabilities":"STAGE_UNSTAGE_VOLUME"}
{"level":"info","timestamp":"2021-12-15T17:20:57.323Z","caller":"ibmcsidriver/ibm_csi_driver.go:144","msg":"Adding node service capability","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver","NodeServiceCapabilities":"GET_VOLUME_STATS"}
{"level":"info","timestamp":"2021-12-15T17:20:57.323Z","caller":"ibmcsidriver/ibm_csi_driver.go:144","msg":"Adding node service capability","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver","NodeServiceCapabilities":"EXPAND_VOLUME"}
{"level":"info","timestamp":"2021-12-15T17:20:57.323Z","caller":"ibmcsidriver/ibm_csi_driver.go:148","msg":"Successfully added Node Service Capabilities","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver"}
{"level":"info","timestamp":"2021-12-15T17:20:57.323Z","caller":"ibmcsidriver/ibm_csi_driver.go:108","msg":"Successfully setup IBM CSI driver","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver"}
{"level":"info","timestamp":"2021-12-15T17:20:57.323Z","caller":"cmd/main.go:106","msg":"Successfully initialized driver...","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver"}
{"level":"info","timestamp":"2021-12-15T17:20:57.323Z","caller":"cmd/main.go:118","msg":"Starting metrics endpoint","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver"}
{"level":"info","timestamp":"2021-12-15T17:20:57.328Z","caller":"ibmcsidriver/ibm_csi_driver.go:193","msg":"IBMCSIDriver-Run...","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver","Endpoint":"unix:/csi/csi.sock"}
{"level":"info","timestamp":"2021-12-15T17:20:57.328Z","caller":"watcher/pv_watcher.go:144","msg":"PVWatcher starting","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver"}
{"level":"info","timestamp":"2021-12-15T17:20:57.328Z","caller":"watcher/pv_watcher.go:147","msg":"PVWatcher started","name":"ibm-vpc-block-csi-driver","CSIDriverName":"IBM VPC block driver"}
{"leve [...]

2021-12-16 08:44 UTC, sameshai commented
Introduce the error in sample code -- 
```
{"level":"info","ts":"2021-12-16T14:12:21.578+0530","caller":"utils/init_provider.go:97","msg":"Successfully fetched provider session","RequestID":"3e0349c3-61a7-48f4-8847-b420231cacd0"}
Enter the volume id: r006-49e26f19-8ac0-4cbc-b649-43cf47b91852
Enter the instance id: kube-c3j7orad03vigk0p57pg-myclusterus-default-000002b2
Enter the cluster id: c3j7orad03vigk0p57pg
{"level":"info","ts":"2021-12-16T14:12:33.181+0530","caller":"provider/attach_volume.go:53","msg":"Validating basic inputs for Attach method...","RequestID":"3e0349c3-61a7-48f4-8847-b420231cacd0","volumeAttachRequest":{"volumeID":"r006-49e26f19-8ac0-4cbc-b649-43cf47b91852","instanceID":"kube-c3j7orad03vigk0p57pg-myclusterus-default-000002b2","vpcVolumeAttachment":{},"iksVolumeAttachment":{"clusterID":"c3j7orad03vigk0p57pg"}}}
{"level":"info","ts":"2021-12-16T14:12:33.181+0530","caller":"provider/attach_volume.go:69","msg":"Checking if volume is already attached by other thread","RequestID":"3e0349c3-61a7-48f4-8847-b420231cacd0"}
{"level":"info","ts":"2021-12-16T14:12:33.181+0530","caller":"provider/get_volume_attachment.go:40","msg":"Validating basic inputs for GetVolumeAttachment method...","RequestID":"3e0349c3-61a7-48f4-8847-b420231cacd0","volumeAttachRequest":{"volumeID":"r006-49e26f19-8ac0-4cbc-b649-43cf47b91852","instanceID":"kube-c3j7orad03vigk0p57pg-myclusterus-default-000002b2","vpcVolumeAttachment":{},"iksVolumeAttachment":{"clusterID":"c3j7orad03vigk0p57pg"}}}
{"level":"info","ts":"2021-12-16T14:12:33.181+0530","caller":"provider/get_volume_attachment.go:92","msg":"Getting VolumeAttachmentList from VPC provider...","RequestID":"3e0349c3-61a7-48f4-8847-b420231cacd0"}
{"level":"info","ts":"2021-12-16T14:12:33.181+0530","caller":"instances/iks_list_volume_attachments.go:47","msg":"Equivalent curl command and query parameters","RequestID":"3e0349c3-61a7-48f4-8847-b420231cacd0","URL":"https://us-south.containers.cloud.ibm.com/v2/storage/vpc/getAttachmentsList?cluster=c3j7orad03vigk0p57pg&generation=2&version=2021-07-02&worker=kube-c3j7orad03vigk0p57pg-myclusterus-default-000002b2","volumeAttachmentTemplate":{"clusterID":"c3j7orad03vigk0p57pg","volume":{"id":"r006-49e26f19-8ac0-4cbc-b649-43cf47b91852"}},"Operation":{"Name":"ListVolumeAttachment","Method":"GET","PathPattern":"v2/storage/vpc/getAttachmentsList"},"cluster":"c3j7orad03vigk0p57pg","worker":"kube-c3j7orad03vigk0p57pg-myclusterus-default-000002b2"}
{"level":"info","ts":"2021-12-16T14:12:35.876+0530","caller":"instances/iks_list_volume_attachments.go:54","msg":"Successfully retrieved the volume attachments","RequestID":"3e0349c3-61a7-48f4-8847-b420231cacd0"}
2021/12/16 14:12:35 TIME TAKEN BY FUNCTION IKS ListVolumeAttachments IS 2.695100214s
{"level":"error","ts":"2021-12-16T14:12:35.876+0530","caller":"provider/get_volume_attachment.go:121","msg":"Volume attachment not found","RequestID":"3e0349c3-61a7-48f4-8847-b420231cacd0"}
{"level":"info","ts":"2021-12-16T14:12:35.876+0530","caller":"provider/get_volume_attachment.go:54","msg":"Volume attachment response","RequestID":"3e0349c3-61a7-48f4-8847-b420231cacd0","volumeAttachmentResponse":null,"error":"{Code:VolumeAttachFindFailed, Type:VolumeAttachFindFailed, Description:No volume attachment could be found for the specified volume ID 'r006-49e26f19-8ac0-4cbc-b649-43cf47b91852' and instance ID 'kube-c3j7orad03vigk0p57pg-myclusterus-default-000002b2'., BackendError:no VolumeAttachment Found, RC:400}"}
{"level":"info","ts":"2021-12-16T14:12:35.877+0530","caller":"provider/attach_volume.go:77","msg":"Attaching volume from VPC provider...","RequestID":"3e0349c3-61a7-48f4-8847-b420231cacd0","IKSEnabled?":true}
{"level":"info","ts":"2021-12-16T14:12:35.877+0530","caller":"instances/iks_attach_volume.go:49","msg":"Equivalent curl command and query parameters","RequestID":"3e0349c3-61a7-48f4-8847-b420231cacd0","URL":"https://us-south.containers.cloud.ibm.com/v2/storage/vpc/createAttachment?cluster=c3j7orad03vigk0p57pg&generation=2&version=2021-07-02&volumeID=r006-49e26f19-8ac0-4cbc-b649-43cf47b91852&worker=kube-c3j7orad03vigk0p57pg-myclusterus-default-000002b2","Payload":{"clusterID":"c3j7orad03vigk0p57pg","volume":{"id":"r006-49e26f19-8ac0-4cbc-b649-43cf47b91852"}},"Operation":{"Name":"AttachVolume","Method":"POST","PathPattern":"v2/storage/vpc/createAttachment"},"cluster":"c3j7orad03vigk0p57pg","worker":"kube-c3j7orad03vigk0p57pg-myclusterus-default-000002b2","volumeID":"r006-49e26f19-8ac0-4cbc-b649-43cf47b91852"}
{"level":"info","ts":"2021-12-16T14:12:40.747+0530","caller":"instances/iks_attach_volume.go:56","msg":"Successfully attached the volume","RequestID":"3e0349c3-61a7-48f4-8847-b420231cacd0"}
2021/12/16 14:12:40 TIME TAKEN BY FUNCTION IKS AttachVolume IS 4.869994957s
{"level":"info","ts":"2021-12-16T14:12:40.747+0530","caller":"metrics/metrics.go:73","msg":"Time to complete","RequestID":"3e0349c3-61a7-48f4-8847-b420231cacd0","AttachVolume":7.565530335}
**{"level":"error","ts":"2021-12-16T14:12:40.747+0530","caller":"samples/attach_detach.go:51","msg":"Failed to attach the volume: ","RequestID":"3e0349c3-61a7-48f4-8847-b420231cacd0","error":"{Code:VolumeAttachFailed, Type:AttachFailed, Description:The volume ID 'r006-49e26f19-8ac0-4cbc-b649-43cf47b91852' could not be attached to the instance ID 'kube-c3j7orad03vigk0p57pg-myclusterus-default-000002b2'., BackendError:volumeAttachmentResult object is not valid, volume information is nil, RC:500}"}**
```

2021-12-16 09:09 UTC, GunaKKIBM approved these changes

2021-12-16 09:12 UTC, prankulmahajan reviewed
Looks good. Can we also add ut?

2021-12-16 09:24 UTC, sameshai commented
> Looks good. Can we also add ut?

Done

2021-12-16 09:45 UTC, prankulmahajan approved these changes
lgtm

2021-12-16 09:58 UTC, GunaKKIBM approved these changes

2021-12-16 09:59 UTC, GunaKKIBM commented
lgtm

2021-12-16 13:15 UTC, arahamad requested changes

2021-12-16 13:15 UTC, arahamad commented on block/provider/attach_volume.go
> +			err = errors.New("volumeAttachmentResult object is not valid, volume information is nil")
can we have a proper message and how user will fix this issue as err was nil

2022-08-26 15:47 UTC, contsto commented
:red_circle: Coverage decreased from [90.3926%] to [87.7868%]

2022-08-29 16:43 UTC, contsto commented
:red_circle: Coverage decreased from [90.3926%] to [87.7868%]

2022-08-30 04:08 UTC, contsto commented
:red_circle: Coverage decreased from [90.3926%] to [87.7868%]

2026-03-10 11:41 UTC, closed without merging