Add support user_tags field in library to append volume lables
IBM/ibmcloud-volume-vpc pull request #43
Opened 2022-05-24 13:27 UTC by sameshai

2022-05-25 07:51 UTC, arahamad approved these changes
lgtm, please verify these changes before merging as we are in process for compute identity release

2022-06-21 04:57 UTC, contsto commented
:red_circle: Coverage decreased from [90.3926%] to [87.7868%]

2022-06-21 06:20 UTC, contsto commented
:red_circle: Coverage decreased from [90.3926%] to [87.7868%]

2022-06-21 06:24 UTC, contsto commented
:red_circle: Coverage decreased from [90.3926%] to [87.7868%]

2022-06-21 11:23 UTC, arahamad requested changes

2022-06-21 11:23 UTC, arahamad commented on block/provider/create_volume.go
> +	if len(vpcs.Config.VPCConfig.ClusterVolumeLabel) != 0 {
can you write this in `validateVolumeRequest` method

2022-06-21 11:23 UTC, arahamad commented on go.mod
> +	github.com/IBM/ibmcloud-volume-interface v1.0.1-beta4.0.20220620123330-2ce06f9f3405
update this with proper release

2022-06-21 12:12 UTC, arahamad approved these changes
lgtm, please verify also

2022-06-21 12:17 UTC, contsto commented
:red_circle: Coverage decreased from [90.3926%] to [87.7868%]

2022-06-21 12:45 UTC, ambiknai approved these changes

2022-06-21 12:46 UTC, merged